
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kizo-api'
    static_configs:
      - targets: ['host.docker.internal:3000'] # ðŸ’¡ Your API port

  - job_name: 'kizo-worker'
    static_configs:
      - targets: ['kizo-processor:3001'] # ðŸ’¡ Your Worker port